### ISSUE TITLE
Add Header and Footer as shared HTML

### ISSUE THREAD

**Issue by edthedev** [app-illinois/Design-Resources#111]
## Context

Currently many files need to  change for the HTML demo site when the page header or footer information need updated.

We have discussed adding a step to `setuppages.sh` that pre-pends and appends a shared `header.html` and `footer.html` file.

https://github.com/app-illinois/Design-Resources/blob/develop/setuppages.sh

## Tasks

- [ ] Copy content from on of the existing pages to create `header.html` and `footer.html`
- [ ] Update `setuppages.sh` to pre-pend `header.html` to pages generated
- [ ] Update `setuppages.sh` to append `footer.html` to pages generated
- [ ] Remove header and footer HTML from all demo HTML pages to prevent duplication
